# Generated by Django 5.0 on 2023-12-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='new_user',
        ),
    ]
